name: HalfCheetah-v2
args: []
kwargs: {}
obs_dim: 17
action_dim: 6
action_min: null
action_max: null

load_dir: "/home/zichang/repo/bet/exp_local/2024.10.08/211720_kitchen_train/"

workspace:
  _target_: workspaces.adept_kitchen.AdeptKitchenWorkspace

dataset_fn:
  _target_: dataloaders.trajectory_loader.get_gym_dataset
  data_directory: ${env_vars.datasets.cheetah}
  window_size: ${window_size}
